<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Xobex.CryptoId</RootNamespace>
    <IsPackable>true</IsPackable>
    <Title>Secure Database ID Obfuscation Library for ASP.NET Core</Title>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Xobex.CryptoId.AspNetCore</PackageId>
    <Version>2.0.2</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
  </PropertyGroup>

  <Import Project="..\Xobex.CryptoId.build.props" />

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xobex.CryptoId\Xobex.CryptoId.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
